[machine]
;Nozzle 0 Top Position in servo degrees (upwards = -)
nozzle0top = 30
;Nozzle 0 Bot Position in servo degrees (upwards = -)
nozzle0bot = 170
;Nozzle 1 Top Position in servo degrees (upwards = +)
nozzle1top = 180
;Nozzle 1 Bot Position in servo degrees (upwards = +)
nozzle1bot = 15
;Difference between Nozzle 0 and Nozzle 1
nozzleoffsetx = 79
;Difference between Nozzle 0 and Nozzle 1
nozzleoffsety = 0
;Clamp base offset. Difference between bed origin and PCB origin 
cbo_x = 82.5
;Clamp base offset. Difference between bed origin and PCB origin 
cbo_y = 96.5

[directories]
;Directories in /files folder where inputs and outputs are stored.
pathplacements = './files/placements.txt'
pathfeeders = './files/feeders.config'
pathpackages = './files/packages.config'